/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MdLabel {
        "concealed": boolean;
        "hidden": boolean;
        "truncate": boolean;
    }
}
declare global {
    interface HTMLMdLabelElement extends Components.MdLabel, HTMLStencilElement {
    }
    var HTMLMdLabelElement: {
        prototype: HTMLMdLabelElement;
        new (): HTMLMdLabelElement;
    };
    interface HTMLElementTagNameMap {
        "md-label": HTMLMdLabelElement;
    }
}
declare namespace LocalJSX {
    interface MdLabel {
        "concealed"?: boolean;
        "hidden"?: boolean;
        "truncate"?: boolean;
    }
    interface IntrinsicElements {
        "md-label": MdLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "md-label": LocalJSX.MdLabel & JSXBase.HTMLAttributes<HTMLMdLabelElement>;
        }
    }
}
