/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MdAppBar {
        "concealed": boolean;
        "hidden": boolean;
    }
    interface MdButton {
        "concealed": boolean;
        "hidden": boolean;
        "icon": string;
    }
    interface MdColumn {
        "concealed": boolean;
        "hidden": boolean;
    }
    interface MdLabel {
        "concealed": boolean;
        "hidden": boolean;
        "truncate": boolean;
    }
    interface MdRow {
        "concealed": boolean;
        "hidden": boolean;
    }
    interface MdSearch {
        "concealed": boolean;
        "hidden": boolean;
        "placeholder": string;
    }
    interface MdSpacer {
        "concealed": boolean;
        "hidden": boolean;
        "width": number;
    }
    interface MdToolbar {
        "concealed": boolean;
        "hidden": boolean;
    }
}
declare global {
    interface HTMLMdAppBarElement extends Components.MdAppBar, HTMLStencilElement {
    }
    var HTMLMdAppBarElement: {
        prototype: HTMLMdAppBarElement;
        new (): HTMLMdAppBarElement;
    };
    interface HTMLMdButtonElement extends Components.MdButton, HTMLStencilElement {
    }
    var HTMLMdButtonElement: {
        prototype: HTMLMdButtonElement;
        new (): HTMLMdButtonElement;
    };
    interface HTMLMdColumnElement extends Components.MdColumn, HTMLStencilElement {
    }
    var HTMLMdColumnElement: {
        prototype: HTMLMdColumnElement;
        new (): HTMLMdColumnElement;
    };
    interface HTMLMdLabelElement extends Components.MdLabel, HTMLStencilElement {
    }
    var HTMLMdLabelElement: {
        prototype: HTMLMdLabelElement;
        new (): HTMLMdLabelElement;
    };
    interface HTMLMdRowElement extends Components.MdRow, HTMLStencilElement {
    }
    var HTMLMdRowElement: {
        prototype: HTMLMdRowElement;
        new (): HTMLMdRowElement;
    };
    interface HTMLMdSearchElement extends Components.MdSearch, HTMLStencilElement {
    }
    var HTMLMdSearchElement: {
        prototype: HTMLMdSearchElement;
        new (): HTMLMdSearchElement;
    };
    interface HTMLMdSpacerElement extends Components.MdSpacer, HTMLStencilElement {
    }
    var HTMLMdSpacerElement: {
        prototype: HTMLMdSpacerElement;
        new (): HTMLMdSpacerElement;
    };
    interface HTMLMdToolbarElement extends Components.MdToolbar, HTMLStencilElement {
    }
    var HTMLMdToolbarElement: {
        prototype: HTMLMdToolbarElement;
        new (): HTMLMdToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "md-app-bar": HTMLMdAppBarElement;
        "md-button": HTMLMdButtonElement;
        "md-column": HTMLMdColumnElement;
        "md-label": HTMLMdLabelElement;
        "md-row": HTMLMdRowElement;
        "md-search": HTMLMdSearchElement;
        "md-spacer": HTMLMdSpacerElement;
        "md-toolbar": HTMLMdToolbarElement;
    }
}
declare namespace LocalJSX {
    interface MdAppBar {
        "concealed"?: boolean;
        "hidden"?: boolean;
    }
    interface MdButton {
        "concealed"?: boolean;
        "hidden"?: boolean;
        "icon"?: string;
    }
    interface MdColumn {
        "concealed"?: boolean;
        "hidden"?: boolean;
    }
    interface MdLabel {
        "concealed"?: boolean;
        "hidden"?: boolean;
        "truncate"?: boolean;
    }
    interface MdRow {
        "concealed"?: boolean;
        "hidden"?: boolean;
    }
    interface MdSearch {
        "concealed"?: boolean;
        "hidden"?: boolean;
        "onSearchCancel"?: (event: CustomEvent<any>) => void;
        "onSearchChange"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
    }
    interface MdSpacer {
        "concealed"?: boolean;
        "hidden"?: boolean;
        "width"?: number;
    }
    interface MdToolbar {
        "concealed"?: boolean;
        "hidden"?: boolean;
    }
    interface IntrinsicElements {
        "md-app-bar": MdAppBar;
        "md-button": MdButton;
        "md-column": MdColumn;
        "md-label": MdLabel;
        "md-row": MdRow;
        "md-search": MdSearch;
        "md-spacer": MdSpacer;
        "md-toolbar": MdToolbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "md-app-bar": LocalJSX.MdAppBar & JSXBase.HTMLAttributes<HTMLMdAppBarElement>;
            "md-button": LocalJSX.MdButton & JSXBase.HTMLAttributes<HTMLMdButtonElement>;
            "md-column": LocalJSX.MdColumn & JSXBase.HTMLAttributes<HTMLMdColumnElement>;
            "md-label": LocalJSX.MdLabel & JSXBase.HTMLAttributes<HTMLMdLabelElement>;
            "md-row": LocalJSX.MdRow & JSXBase.HTMLAttributes<HTMLMdRowElement>;
            "md-search": LocalJSX.MdSearch & JSXBase.HTMLAttributes<HTMLMdSearchElement>;
            "md-spacer": LocalJSX.MdSpacer & JSXBase.HTMLAttributes<HTMLMdSpacerElement>;
            "md-toolbar": LocalJSX.MdToolbar & JSXBase.HTMLAttributes<HTMLMdToolbarElement>;
        }
    }
}
