/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IosCalendar {
        "focused": Date;
        "hidden": boolean;
        "selected": Date;
    }
    interface IosDatePicker {
        "open": boolean;
        "value": Date;
    }
    interface IosMonth {
        "focused": Date;
        "selected": Date;
    }
}
declare global {
    interface HTMLIosCalendarElement extends Components.IosCalendar, HTMLStencilElement {
    }
    var HTMLIosCalendarElement: {
        prototype: HTMLIosCalendarElement;
        new (): HTMLIosCalendarElement;
    };
    interface HTMLIosDatePickerElement extends Components.IosDatePicker, HTMLStencilElement {
    }
    var HTMLIosDatePickerElement: {
        prototype: HTMLIosDatePickerElement;
        new (): HTMLIosDatePickerElement;
    };
    interface HTMLIosMonthElement extends Components.IosMonth, HTMLStencilElement {
    }
    var HTMLIosMonthElement: {
        prototype: HTMLIosMonthElement;
        new (): HTMLIosMonthElement;
    };
    interface HTMLElementTagNameMap {
        "ios-calendar": HTMLIosCalendarElement;
        "ios-date-picker": HTMLIosDatePickerElement;
        "ios-month": HTMLIosMonthElement;
    }
}
declare namespace LocalJSX {
    interface IosCalendar {
        "focused"?: Date;
        "hidden"?: boolean;
        "onCalendarChange"?: (event: CustomEvent<Date>) => void;
        "selected"?: Date;
    }
    interface IosDatePicker {
        "open"?: boolean;
        "value"?: Date;
    }
    interface IosMonth {
        "focused"?: Date;
        "onMonthChange"?: (event: CustomEvent<Date>) => void;
        "selected"?: Date;
    }
    interface IntrinsicElements {
        "ios-calendar": IosCalendar;
        "ios-date-picker": IosDatePicker;
        "ios-month": IosMonth;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ios-calendar": LocalJSX.IosCalendar & JSXBase.HTMLAttributes<HTMLIosCalendarElement>;
            "ios-date-picker": LocalJSX.IosDatePicker & JSXBase.HTMLAttributes<HTMLIosDatePickerElement>;
            "ios-month": LocalJSX.IosMonth & JSXBase.HTMLAttributes<HTMLIosMonthElement>;
        }
    }
}
