/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IbmButton {
        "concealed": boolean;
        "disabled": boolean;
        "hidden": boolean;
        "icon": string;
        "kind": string;
        "size": string;
    }
    interface IbmLabel {
        "concealed": boolean;
        "data": any;
        "disabled": boolean;
        "hidden": boolean;
        "internal": boolean;
        "truncate": boolean;
    }
    interface IbmLink {
        "concealed": boolean;
        "data": any;
        "disabled": boolean;
        "hidden": boolean;
        "href": string;
        "inline": boolean;
    }
}
declare global {
    interface HTMLIbmButtonElement extends Components.IbmButton, HTMLStencilElement {
    }
    var HTMLIbmButtonElement: {
        prototype: HTMLIbmButtonElement;
        new (): HTMLIbmButtonElement;
    };
    interface HTMLIbmLabelElement extends Components.IbmLabel, HTMLStencilElement {
    }
    var HTMLIbmLabelElement: {
        prototype: HTMLIbmLabelElement;
        new (): HTMLIbmLabelElement;
    };
    interface HTMLIbmLinkElement extends Components.IbmLink, HTMLStencilElement {
    }
    var HTMLIbmLinkElement: {
        prototype: HTMLIbmLinkElement;
        new (): HTMLIbmLinkElement;
    };
    interface HTMLElementTagNameMap {
        "ibm-button": HTMLIbmButtonElement;
        "ibm-label": HTMLIbmLabelElement;
        "ibm-link": HTMLIbmLinkElement;
    }
}
declare namespace LocalJSX {
    interface IbmButton {
        "concealed"?: boolean;
        "disabled"?: boolean;
        "hidden"?: boolean;
        "icon"?: string;
        "kind"?: string;
        "size"?: string;
    }
    interface IbmLabel {
        "concealed"?: boolean;
        "data"?: any;
        "disabled"?: boolean;
        "hidden"?: boolean;
        "internal"?: boolean;
        "truncate"?: boolean;
    }
    interface IbmLink {
        "concealed"?: boolean;
        "data"?: any;
        "disabled"?: boolean;
        "hidden"?: boolean;
        "href"?: string;
        "inline"?: boolean;
    }
    interface IntrinsicElements {
        "ibm-button": IbmButton;
        "ibm-label": IbmLabel;
        "ibm-link": IbmLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ibm-button": LocalJSX.IbmButton & JSXBase.HTMLAttributes<HTMLIbmButtonElement>;
            "ibm-label": LocalJSX.IbmLabel & JSXBase.HTMLAttributes<HTMLIbmLabelElement>;
            "ibm-link": LocalJSX.IbmLink & JSXBase.HTMLAttributes<HTMLIbmLinkElement>;
        }
    }
}
